name: jasper-reporting-service

on: [push]

jobs:
  build:
    env:
      DOCKER_ACCOUNT: sogis
      DOCKER_REPO: jasper-reporting-service
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
          repository: qwc-services/jasper-reporting-service
          path: jasper-reporting-service
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install fonts.jar
        run: |
          mvn -f jasper-reporting-service/pom.xml install:install-file -Dfile=demo/fonts/fonts-extension.jar -DgroupId=local.jasperFontOverrides -DartifactId=local.jasperFontOverrides -Dversion=1.0 -Dpackaging=jar -DlocalRepositoryPath=$HOME/.m2/repository
      - name: Build jar with maven
          run:
            mvn package
      - name: List all files (test)
        run: ls -la 
  
