name: jasper-reporting-service

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
    

jobs:
  build:
    env:
      DOCKER_ACCOUNT: sogis
      #DOCKER_REPO: jasper-reporting-service
      #DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USER}}      
      BUILD_NUMBER: ${{GITHUB_RUN_NUMBER}}      
    runs-on: ubuntu-latest

    # todo cache
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
          repository: qwc-services/jasper-reporting-service
          path: jasper-reporting-service
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install fonts.jar
        run: |
          mvn -f jasper-reporting-service/pom.xml install:install-file -Dfile=../fonts-extension.jar -DgroupId=local.jasperFontOverrides -DartifactId=local.jasperFontOverrides -Dversion=1.0 -Dpackaging=jar -DlocalRepositoryPath=$HOME/.m2/repository
      - name: Build jar with maven
        run:
          mvn -f jasper-reporting-service/pom.xml package
      - name: List all files (test)
        run: ls -la jasper-reporting-service/target
      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sogis/jasper-reporting-service
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "latest,${{ env.BUILD_NUMBER }}"

  
